// Generate / verify the precomputed Meggitt-decoder syndrome bitmap for
// BCH(31,21) (POCSAG generator polynomial 0x769). Builds the bitmap from
// the polynomial via a length-10 LFSR, then prints it as a C array suitable
// for pasting into bch.c (BCH_MEGGITT_TABLE_MODE_CONST mode).
//
// Build: cc tools/gen_meggitt_table.c -o gen_meggitt_table
//
#include <stdio.h>
#include <stdint.h>

#define BCH_N         31U
#define BCH_R         10U
#define BCH_GEN_POLY  0x769U
#define BCH_GEN_HIGH  (1U << BCH_R)

int main(void)
{
    uint8_t bitmap[(1U << BCH_R) / 8U] = {0};

    uint16_t pow_x[BCH_N];
    uint16_t v = 1U;
    for (uint32_t k = 0; k < BCH_N; k++) {
        pow_x[k] = v;
        v <<= 1;
        if (v & BCH_GEN_HIGH) v ^= BCH_GEN_POLY;
    }
    const uint16_t s_msb = pow_x[BCH_N - 1];

    bitmap[s_msb >> 3] |= (uint8_t)(1U << (s_msb & 7U));
    for (uint32_t k = 0; k < BCH_N - 1; k++) {
        const uint16_t s = (uint16_t)(s_msb ^ pow_x[k]);
        bitmap[s >> 3] |= (uint8_t)(1U << (s & 7U));
    }

    printf("// Auto-generated by tools/gen_meggitt_table.c -- do not edit by hand.\n");
    printf("// 1024-bit bitmap of MSB-error syndromes for BCH(31,21), g(x)=0x%X.\n",
           BCH_GEN_POLY);
    printf("#define BCH_MEGGITT_MSB_SYNDROME 0x%03Xu  // x^30 mod g(x)\n", s_msb);
    printf("static const uint8_t bch_meggitt_msb_error_bitmap[%zu] = {",
           sizeof(bitmap));
    for (size_t i = 0; i < sizeof(bitmap); i++) {
        if ((i % 8) == 0) printf("\n    ");
        printf("0x%02X,", bitmap[i]);
        if ((i % 8) != 7) printf(" ");
    }
    printf("\n};\n");
    return 0;
}
